### ISSUE TITLE
Fix privileged names

### ISSUE THREAD

**Issue by acoppock** [egap/registration#12]
In particular, with the pre_register() function.  Where's the best place to name each of

clust_var
block_var
treatment_variable
condition_names
outcome_name

Also, in the summary of the model, we're getting things like ZZ1 -- should just get the condition_name?

**Comment by graemeblair** [comment]
I fixed treatment_variable dependencies in pre_register(). I think most of these will be fixed by a new declare_design() which has variable names rather than vectors, and in general is less dependent on a first mock realization of the data. Does that sound right?

Opening separate issue for the ZZ1 issue.

**Comment by graemeblair** [comment]
Closing this because it will be addressed with the new declare_design in 0.2 version
