### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by acoppock** [egap/registration#6]
Right now, we depend on

1. rmarkdown
2. xtable

can we add
3. ggplot2 for default plots?

**Comment by macartan** [comment]
My preferences is for as few dependencies as possible.
rmarkdown is inevitable for what we want I think; moreoever (I think) if
someone does not want to use it for whatever reason they an still create
all the objects/

xtable --  are we sure we need? Turning a matrix into a simple latex table
is very easy and can be done with a few lines of paste with appropriate &
and \\ markers.

ggplot2; I am not nearly as convinced of the utility of this except for
particular types of graphs; the base functions allow enormous flexibility.
for some things though like heatmaps and matrices of plots ggplot2 is
better ; I think if we have a clear need for a ggplot2 functionality we
should do it; but not if it is just because we prefer default aesthetics or
because we prefer one line of code instead of 2. do we?

**Comment by acoppock** [comment]
I can give in on ggplot2 :).  But I think that xtable is worth depending on; it's super-stable at this point and will greatly simplify our lives.  Custom .tex files are easy enough to write, but they aren't flexible or extensible like xtable -- plus, xtable has the ability to output html tables too, which we might want to be able to do if ever folks wanted their .rmd's to produce html files instead...

**Comment by macartan** [comment]
ok!

On Sat, Jun 20, 2015 at 1:35 PM, Alexander Coppock <notifications@github.com
