### ISSUE TITLE
making design function inherit characteristics from covariates and potential_outcomes objects

### ISSUE THREAD

**Issue by graemeblair** [egap/registration#7]
Even though we've decided to create potential outcomes independent of the design declaration, i.e. there can be more potential outcomes declared than used in the design, it would be ideal if the design object could figure out or be told the names of the conditions based on the output of declare_potential_outcomes().

Related, Alex and I discussed yesterday changing design so that the arguments are characters indicating the variable names that will be used to indicate blocks and clusters and be sent a data object as argument. Propose we hold off on both changes so we can discuss on phone various workflow issues that go into this (i.e. using external blocking tools, whether there must be a realization of the data before design, etc.) 

So just raising this to remember it for our next conversation.

**Comment by graemeblair** [comment]
To add to this, I wonder if we also need a way a more flexible way to have condition names correspond to values of the treatment assignment (i.e. output of ra_fun()). Right now as I understand ra_fun() returns integer values which are associated (in order?) with the condition_names output. We could use factors for example or string variables depending on what the user names their conditions in declare_potential_outcomes().

**Comment by acoppock** [comment]
I've come around the the philosophy that declare_potential_outcomes() should pluck out of the infinity of potential outcomes some subset of POs for intellectual consideration, some subset of which can in turn be revealed by an experimental design.

In order to harmonize our work flow with the superpopulation philosophy (which I've also come around to, thanks for all your patience there, folks...), we'll need declare_design() to either be able to accept a real dataframe or a make_data() function.  

One frustration will be that we won't know in advance the exact number of units in each block (i.e., a blocking algorithm could very well end up with different numbers in each block in each simulation).  That means that very specific design declarations (e.g., something that uses the block_m argument) might break from sim to sim. Maybe this is an acceptable limitation.

Re: output of ra_fun(), it returns a character vector whose entries are the unique values of condition_names.

**Comment by jaspercooper** [comment]
We could just embed make_data() inside get_power(), in which case you would just need to feed the outcomes and the covariates objects into get_power() somehow (perhaps by having them stored inside the design object).

**Comment by graemeblair** [comment]
I think still you want declare_design() to take a data frame or the PO and
covariate objects, for the purpose of defining the design to begin with.

**Comment by jaspercooper** [comment]
Right, exactly. So imagine you have an option in get_power() called resample = TRUE / FALSE. 

If you give declare_design a pre-made matrix, and set resample to TRUE, you get an error (unless we want to include bootstrapping, which could be tricky in the case of clusters). It can only do power analysis based on the RA method. 

But if you have given declare_design the covariates_object and the outcomes_object, and you set resample to TRUE, then each iteration of get_power can simply use make_data to generate a new data frame (or maybe you resample once and then do 100-1000 RAs, and take that as one estimate of the power, then average the power over the possible samples you may have drawn). That way you can get both the uncertainty from sampling from the superpopulation and the uncertainty from the RA method and sample size when estimating your power.

**Comment by macartan** [comment]
Resampling arguments (resample_cov, resampl_po) sounds right; but in my understanding this wouldn't be in declare_design but later, eg in make_power. 

declare_design should be able to work with simulation invariant features of the data; eg *that* there are blocks, not what the blocks are. Similarly the quantities assessed in get_power should be simulation invariant features, eg the variation explained by blocks, not the fixed effects for given blocks. 
Alex has concerns for bugs here adn I'd like to get more of a sense of that. Is it things like your analysis function cannot say to control for A and B say, since in a given draw of data, eitehr A or B may have no variation?

**Comment by jaspercooper** [comment]
Sure, it should absolutely be done by get_power, I meant simply that we don't need to give get_power the design, outcomes and covariates objects, since it would make sense for the latter two to be contained within the former. 

Alex, I'd also like to get a sense of what issues you think might arise with the resampling, and whether / how they could be solved by giving make_data some methods for avoiding hiccups. At present make_data can handle block and cluster structures that are either fixed or vary from permutation to permutation, but I could also put in some constraints. I also need to figure out a way to automate the population of the various levels when the user doesn't specify anything, so this might be another area where we can try to avoid some bugs.

**Comment by graemeblair** [comment]
Implemented this in get_power() - it can take either a data argument alone or one or both of a covariates object and a potential_outcomes object. If it gets data it doesn't resample, if it gets one or both of the others it resamples both.
